/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente;

import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import servidor.Mensagem;

/**
 *
 * @author Robson Gomes
 */
public class JFrameChatPrivate extends javax.swing.JFrame {
    
    //Variaveis globais
    
    ThreadCliente t;
    Mensagem data;
    
    /**
     * Creates new form JFrameChatPrivate
     * @param t
     * @param data
     */
    public JFrameChatPrivate(ThreadCliente t, Mensagem data) {
        initComponents();
        initJChatPrivate();
        this.t = t;
        this.data = data;
        Mensagem m = data;
        System.out.println("TO: " + m.getTo());
        System.out.println("TOPort: " + m.getToPort());
        System.out.println("From: " + m.getFrom());
        System.out.println("FromPort: " + m.getFromPort());  
    }

    private JFrameChatPrivate() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    private void initJChatPrivate(){
        try {
            jTextMessageInputPrivate.requestFocus();                                                
            
        } catch(HeadlessException ex) {
            System.out.println(ex.getMessage());
        }
    }

    public Mensagem getData() {
        return data;
    }        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextMessageViewsPrivate = new javax.swing.JTextArea();
        jTextMessageInputPrivate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jTextMessageViewsPrivate.setColumns(20);
        jTextMessageViewsPrivate.setRows(5);
        jTextMessageViewsPrivate.setEnabled(false);
        jScrollPane1.setViewportView(jTextMessageViewsPrivate);

        jTextMessageInputPrivate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextMessageInputPrivateKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
            .addComponent(jTextMessageInputPrivate)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextMessageInputPrivate, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        t.removerChatsPrivate(this);        
    }//GEN-LAST:event_formWindowClosed
    
    public void newMessage(String conteudo, String from, int fromPort) {
        String message = from + ": " + conteudo + "\n";
        jTextMessageViewsPrivate.setText(jTextMessageViewsPrivate.getText() + message);
    }
    
    private void jTextMessageInputPrivateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextMessageInputPrivateKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) { 
            newMessage(jTextMessageInputPrivate.getText(), data.getFrom(), data.getFromPort());
            
            Mensagem m = new Mensagem();            
            m.setMensagemForOne(true);
            m.setFrom(data.getFrom());
            m.setFromPort(data.getFromPort());
            m.setTo(data.getTo());
            m.setToPort(data.getToPort());
            m.setConteudo(jTextMessageInputPrivate.getText());
            
//            System.out.println("TO: " + m.getTo());
//            System.out.println("TOPort: " + m.getToPort());
//            System.out.println("From: " + m.getFrom());
//            System.out.println("FromPort: " + m.getFromPort());       
            
            try {
                t.getEnviaServ().writeObject(m);
                t.EnviaServ.reset();
            } catch (IOException ex) {
                Logger.getLogger(JFrameChatPrivate.class.getName()).log(Level.SEVERE, null, ex);
            }            
            
            jTextMessageInputPrivate.setText("");
        }
    }//GEN-LAST:event_jTextMessageInputPrivateKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameChatPrivate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameChatPrivate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameChatPrivate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameChatPrivate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameChatPrivate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextMessageInputPrivate;
    private javax.swing.JTextArea jTextMessageViewsPrivate;
    // End of variables declaration//GEN-END:variables
}
